appname = casdoor
httpport = 8000
runmode = prod
SessionOn = true
copyrequestbody = true
driverName = postgres
dataSourceName =
dbName = postgres
tableNamePrefix = casdoor_
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100
enableGzip = true
origin = https://auth.jyrac.stki.org
